"""Extract the exact-arithmetic skeleton of the margin certificates into
Lean 4.

Reads the canonical certificate JSONs of the two-variable verification at
a margin and emits self-contained Lean 4 files whose kernel-checked
theorems restate, over the integers, the exact-rational claims the Python
layer checks with ``fractions.Fraction``:

  1. Star interior (huang_star_interior_<tag>.json): from the serialized
     arb packets, the perturbation matrix is orientation-preserving with
     a positive corner-minimum determinant, and the certificate's
     conclusion chain holds over packet endpoints:
     inradius_lo > required_hi and inradius_lo > the policy floor.
  2. Region II sweep (huang_sweep_<tag>.json): the schedule is exactly
     the n1 x n2 grid tiling of the sweep rectangle (boundary chains per
     axis, no gaps, overlaps, duplicates, or reorderings), and every
     record index appears exactly once.
  3. Region I (huang_region1_<tag>.json): the radius levels chain
     exactly from T_LONG down to T_IN with the final [0, T_IN] band
     present, and within each level the angular chunks tile their
     declared arcs end to end.
  4. Stage 2 (huang_sweep2_<tag>.json): the schedule tiles the expanded
     exclusion box exactly, and the manifest binds the Region-I manifest
     hash it consumed.

Schedule endpoints in these manifests are ``repr(float)`` strings ---
shortest round-trip decimals of the exact binary doubles --- so parsing
them as exact decimal rationals preserves every equality the schedule
was built with; shared cell edges are the same double and hence the
same rational.  Every rational claim is integer-cleared (positive
denominators, so order is preserved).  The same extracted data is
re-checked here with Fraction arithmetic (the mirror) so an extraction
bug cannot silently weaken the Lean claims: mirror failure aborts
generation.

Display-rounded strings (the slab-certificate check enclosures, the
Hessian logs) are deliberately NOT extracted: they are not outward-
exact serializations.  Extending the slab manifests with arb packets,
and this extractor with the corresponding sign families, is recorded
future work.

This is not a formalization of the analytic mathematics; it
kernel-checks the exact combinatorial and algebraic layer of the
certificate chain in a second, foreign proof system.

Usage: python extract_margin.py --results ../results --tag 0p05
       --out generated
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from fractions import Fraction

DEFS = r'''-- Auto-generated by extract_margin.py; self-contained (no imports).
-- Exact-arithmetic skeleton checks, kernel-decided over Int/Nat.
set_option maxHeartbeats 4000000
set_option maxRecDepth 8192

/-- Strict rational order a/b < c/d with positive denominators. -/
def fracLt : Int × Int × Int × Int → Bool
  | (a, b, c, d) => decide (0 < b) && decide (0 < d) && decide (a * d < c * b)

/-- Exact rational equality by cross-multiplication (positive denominators). -/
def fracEq : Int × Int × Int × Int → Bool
  | (a, b, c, d) => decide (0 < b) && decide (0 < d) && decide (a * d = c * b)

/-- A boundary chain: every interval is nonempty (lo < hi as exact
    rationals) and consecutive intervals share their endpoint exactly
    (hi_k = lo_{k+1}) --- no gaps, overlaps, duplicates, or reversals.
    Input: [(lo1,d1,hi1,e1), (lo2,d2,hi2,e2), ...]. -/
def chainOk : List (Int × Int × Int × Int) → Bool
  | [] => true
  | (x :: xs) =>
    let rec go : (Int × Int × Int × Int) → List (Int × Int × Int × Int) → Bool
      | _, [] => true
      | (_, _, h, e), (y :: ys) =>
        fracEq (h, e, y.1, y.2.1) &&
        fracLt (y.1, y.2.1, y.2.2.1, y.2.2.2) && go y ys
    fracLt (x.1, x.2.1, x.2.2.1, x.2.2.2) && go x xs

def allEq (xs : List (Int × Int × Int × Int)) : Bool := xs.all fracEq
def allLt (xs : List (Int × Int × Int × Int)) : Bool := xs.all fracLt

/-- Arb packet proves strict positivity: 0 <= rad and 0 < mid - rad. -/
def posPacket : Int × Int → Bool
  | (mid, rad) => decide (0 <= rad) && decide (0 < mid - rad)

/-- Determinant corner minimum for a 2x2 packet matrix with entries
    (m, r) scaled to one common power of ten: the products a00*a11 and
    a01*a10 are bracketed by their endpoint-corner extremes, and
    min(a00*a11) - max(a01*a10) must be positive. -/
def detPos : Int × Int × Int × Int × Int × Int × Int × Int → Bool
  | (m00, r00, m01, r01, m10, r10, m11, r11) =>
    let lo := fun (m r : Int) => m - r
    let hi := fun (m r : Int) => m + r
    let pmin := fun (a b c d : Int) =>
      min (min (a * c) (a * d)) (min (b * c) (b * d))
    let pmax := fun (a b c d : Int) =>
      max (max (a * c) (a * d)) (max (b * c) (b * d))
    decide (0 <= r00) && decide (0 <= r01) &&
    decide (0 <= r10) && decide (0 <= r11) &&
    decide (pmax (lo m01 r01) (hi m01 r01) (lo m10 r10) (hi m10 r10)
            < pmin (lo m00 r00) (hi m00 r00) (lo m11 r11) (hi m11 r11))
'''


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for block in iter(lambda: f.read(1 << 20), b''):
            h.update(block)
    return h.hexdigest()


def dec_fraction(text) -> Fraction:
    """Exact rational of a decimal string or of a float via its shortest
    round-trip repr.

    Some manifests serialize schedule endpoints as strings (the sweeps),
    others as raw JSON numbers (the Region-I bands).  For the latter,
    repr(float) is injective and order-preserving on doubles, and shared
    cell edges are the same double, hence the same rational --- so every
    chain equality and strict order the checks assert holds for the
    mapped rationals exactly when it holds for the schedule itself."""
    if isinstance(text, (int,)) and not isinstance(text, bool):
        return Fraction(text)
    if isinstance(text, float):
        text = repr(text)
    s = str(text).strip()
    if 'e' in s or 'E' in s:
        mant, exp = s.replace('E', 'e').split('e')
        return dec_fraction(mant) * Fraction(10) ** int(exp)
    return Fraction(s)


def lean_int(v: int) -> str:
    return f'({v})' if v < 0 else str(v)


def frac_pair(x: Fraction):
    return x.numerator, x.denominator


def chain_tuples(intervals):
    """[(lo, hi)] as Fractions -> Lean chain tuples + mirror check."""
    out = []
    for k, (lo, hi) in enumerate(intervals):
        if not lo < hi:
            raise ValueError(f'reversed interval at {k}: {lo} >= {hi}')
        if k + 1 < len(intervals) and hi != intervals[k + 1][0]:
            raise ValueError(f'gap/overlap after interval {k}')
        nl, dl = frac_pair(lo)
        nh, dh = frac_pair(hi)
        out.append((nl, dl, nh, dh))
    return out


def emit(path, name, body):
    text = DEFS + '\n' + body
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    return sha256_file(path)


def eq_tuples(pairs):
    out = []
    for a, b in pairs:
        if a != b:
            raise ValueError(f'mirror equality failed: {a} != {b}')
        na, da = frac_pair(a)
        nb, db = frac_pair(b)
        out.append((na, da, nb, db))
    return out


def lt_tuples(pairs):
    out = []
    for a, b in pairs:
        if not a < b:
            raise ValueError(f'mirror order failed: {a} >= {b}')
        na, da = frac_pair(a)
        nb, db = frac_pair(b)
        out.append((na, da, nb, db))
    return out


def lean_list4(ts):
    rows = ', '.join(
        f'({lean_int(a)}, {lean_int(b)}, {lean_int(c)}, {lean_int(d)})'
        for a, b, c, d in ts)
    return f'[{rows}]'


# ---------------------------------------------------------------------------
# Family 1: star interior
# ---------------------------------------------------------------------------

def packet(record):
    required = {'format', 'mid10', 'rad10', 'exp10', 'digits'}
    if set(record) != required or record['format'] != 'arb-midrad10-v1':
        raise ValueError('invalid packet')
    mid = int(record['mid10'])
    rad = int(record['rad10'])
    if rad < 0 or str(mid) != record['mid10'] or str(rad) != record['rad10']:
        raise ValueError('non-canonical packet integers')
    return mid, rad, int(record['exp10'])


def packet_endpoints(record):
    mid, rad, exp10 = packet(record)
    scale = Fraction(10 ** exp10) if exp10 >= 0 \
        else Fraction(1, 10 ** -exp10)
    return (mid - rad) * scale, (mid + rad) * scale


def extract_star_interior(path, out_dir):
    data = json.load(open(path))
    if data.get('kind') != 'huang_star_interior_certificate':
        raise ValueError('wrong kind')
    m = data['matrix']
    pk = [packet(m[i][j]) for i in range(2) for j in range(2)]
    exps = {e for (_, _, e) in pk}
    shift = min(exps)
    scaled = []
    for (mid, rad, e) in pk:
        s = 10 ** (e - shift)
        scaled.extend([mid * s, rad * s])
    # mirror: Fraction corner determinant
    ep = [packet_endpoints(m[i][j]) for i in range(2) for j in range(2)]
    lo00, hi00 = ep[0]
    lo01, hi01 = ep[1]
    lo10, hi10 = ep[2]
    lo11, hi11 = ep[3]
    dmin = min(a * b for a in (lo00, hi00) for b in (lo11, hi11))
    dmax = max(a * b for a in (lo01, hi01) for b in (lo10, hi10))
    if not dmax < dmin:
        raise ValueError('mirror determinant corner check failed')
    b = data['bounds']
    inr_lo, _ = packet_endpoints(b['inradius'])
    _, req_hi = packet_endpoints(b['required_radius'])
    floor = Fraction('0.0135')
    lt = lt_tuples([(req_hi, inr_lo), (floor, inr_lo)])
    body = f'''
def siMatrix : Int × Int × Int × Int × Int × Int × Int × Int :=
  ({', '.join(lean_int(v) for v in scaled)})

def siChain : List (Int × Int × Int × Int) := {lean_list4(lt)}

theorem si_det_pos : detPos siMatrix = true := by decide
theorem si_chain : allLt siChain = true := by decide
'''
    return emit(os.path.join(out_dir, 'SI_bounds.lean'), 'SI', body)


# ---------------------------------------------------------------------------
# Family 2/4: grid schedules (Region II sweep, stage 2)
# ---------------------------------------------------------------------------

def extract_grid_schedule(path, out_dir, name, rect=None):
    """rect: optional ((a1lo, a1hi), (a2lo, a2hi)) as Fractions the outer
    boundaries must equal (the declared sweep rectangle)."""
    data = json.load(open(path))
    sched = data['schedule']
    cells = [tuple(dec_fraction(x) for x in cell) for cell in sched]
    a1_bounds = sorted({c[0] for c in cells} | {c[1] for c in cells})
    a2_bounds = sorted({c[2] for c in cells} | {c[3] for c in cells})
    n1 = len(a1_bounds) - 1
    n2 = len(a2_bounds) - 1
    if len(sched) != n1 * n2:
        raise ValueError(f'schedule count {len(sched)} != {n1}x{n2}')
    expect = {(a1_bounds[i], a1_bounds[i + 1], a2_bounds[j],
               a2_bounds[j + 1]) for i in range(n1) for j in range(n2)}
    if set(cells) != expect or len(set(cells)) != len(cells):
        raise ValueError('schedule is not the exact grid tiling')
    eqs = []
    if rect is not None:
        (r1lo, r1hi), (r2lo, r2hi) = rect
        eqs = eq_tuples([(a1_bounds[0], r1lo), (a1_bounds[-1], r1hi),
                         (a2_bounds[0], r2lo), (a2_bounds[-1], r2hi)])
    ch1 = chain_tuples(list(zip(a1_bounds[:-1], a1_bounds[1:])))
    ch2 = chain_tuples(list(zip(a2_bounds[:-1], a2_bounds[1:])))
    rect_block = ''
    if eqs:
        rect_block = f'''
def {name}Rect : List (Int × Int × Int × Int) := {lean_list4(eqs)}

theorem {name}_rect : allEq {name}Rect = true := by decide
'''
    body = f'''
def {name}Ax1 : List (Int × Int × Int × Int) := {lean_list4(ch1)}
def {name}Ax2 : List (Int × Int × Int × Int) := {lean_list4(ch2)}

theorem {name}_ax1 : chainOk {name}Ax1 = true := by decide
theorem {name}_ax2 : chainOk {name}Ax2 = true := by decide
{rect_block}
-- {n1} x {n2} grid, {len(sched)} cells.
'''
    return emit(os.path.join(out_dir, f'{name}.lean'), name, body)


# ---------------------------------------------------------------------------
# Family 3: Region I band schedule
# ---------------------------------------------------------------------------

def extract_region1_bdef(path, out_dir):
    """Loewner-majorant definiteness per band, when the manifest carries
    exact B-matrix packets (runs after 2026-07-14 do; earlier manifests
    are skipped with a note).  Claims per band, at one common power of
    ten: b11_lo > 0, b22_lo > 0, b11_lo * b22_lo > max|b12 endpoint|^2."""
    data = json.load(open(path))
    packs = [rec.get('bmat_packets') for rec in data['results']]
    if not any(packs):
        print('  note: no bmat_packets in this manifest; B-definiteness '
              'family skipped (pre-packet run)')
        return None
    rows = []
    for rec in data['results']:
        p = rec.get('bmat_packets')
        if p is None:
            raise ValueError('mixed packet presence across bands')
        (m11, r11, e11), (m12, r12, e12), (m22, r22, e22) = \
            (packet(x) for x in p)
        shift = min(e11, e12, e22)
        s11, s12, s22 = (10 ** (e11 - shift), 10 ** (e12 - shift),
                         10 ** (e22 - shift))
        m11, r11 = m11 * s11, r11 * s11
        m12, r12 = m12 * s12, r12 * s12
        m22, r22 = m22 * s22, r22 * s22
        # mirror
        lo11, lo22 = m11 - r11, m22 - r22
        b = max(abs(m12 - r12), abs(m12 + r12))
        if not (lo11 > 0 and lo22 > 0 and b * b < lo11 * lo22):
            raise ValueError('mirror B-definiteness failed')
        rows.append((m11, r11, m22, r22, m12, r12))
    lists = ',\n  '.join(
        f'({lean_int(a)}, {lean_int(b_)}, {lean_int(c)}, {lean_int(d)}, '
        f'{lean_int(e)}, {lean_int(f)})' for a, b_, c, d, e, f in rows)
    body = f'''
def bDefOk : Int × Int × Int × Int × Int × Int → Bool
  | (m11, r11, m22, r22, m12, r12) =>
    let l11 := m11 - r11
    let l22 := m22 - r22
    let b := (max (m12 - r12).natAbs (m12 + r12).natAbs : Int)
    decide (0 < l11) && decide (0 < l22) && decide (b * b < l11 * l22)

def r1BMat : List (Int × Int × Int × Int × Int × Int) := [
  {lists}]

theorem r1_bdef : r1BMat.all bDefOk = true := by decide
'''
    return emit(os.path.join(out_dir, 'R1BDef.lean'), 'R1BDef', body)


def extract_region1_schedule(path, out_dir):
    data = json.load(open(path))
    bands = [tuple(dec_fraction(x) for x in rec['band'])
             for rec in data['results']]
    fails = [rec for rec in data['results'] if not rec.get('ok')]
    if fails:
        raise ValueError(f'{len(fails)} failed bands; not extractable as '
                         f'a certificate')
    levels = {}
    for (t0, t1, th0, th1) in bands:
        levels.setdefault((t0, t1), []).append((th0, th1))
    radii = sorted(levels, key=lambda p: p[0])
    if radii[0][0] != 0:
        raise ValueError('no origin band')
    rad_chain = chain_tuples(radii)
    # per radius level, split the sorted chunks into maximal runs whose
    # seams chain exactly; each run becomes one Lean chainOk list, so the
    # kernel re-decides both the seam equalities and every chunk's
    # nonemptiness.  Runs may not overlap (mirror check).
    runs = []
    n_chunks = 0
    for key in radii:
        arcs = sorted(levels[key])
        n_chunks += len(arcs)
        run = [arcs[0]]
        for (a, b) in arcs[1:]:
            if run[-1][1] == a:
                run.append((a, b))
            elif run[-1][1] > a:
                raise ValueError('overlapping angular chunks')
            else:
                runs.append(run)
                run = [(a, b)]
        runs.append(run)
    run_tuples = [chain_tuples(run) for run in runs]
    run_lists = '\n'.join(
        f'def r1Run{k} : List (Int × Int × Int × Int) := '
        f'{lean_list4(ts)}' for k, ts in enumerate(run_tuples))
    run_thms = '\n'.join(
        f'theorem r1_run{k} : chainOk r1Run{k} = true := by decide'
        for k in range(len(run_tuples)))
    body = f'''
def r1Radii : List (Int × Int × Int × Int) := {lean_list4(rad_chain)}
{run_lists}

theorem r1_radii : chainOk r1Radii = true := by decide
{run_thms}

-- {len(runs)} angular runs over {len(radii)} radius levels,
-- {n_chunks} chunks in all.
'''
    return emit(os.path.join(out_dir, 'R1Schedule.lean'), 'R1', body)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--results', default=os.path.join('..', 'results'))
    ap.add_argument('--tag', default='0p05')
    ap.add_argument('--out', default='generated')
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    r = args.results
    t = args.tag
    manifest = {'inputs': {}, 'outputs': {}}
    def sweep_rect(p, o):
        pol = json.load(open(p))['policy']
        a1m = dec_fraction(pol['A1MAX'])
        a2m = dec_fraction(pol['A2MAX'])
        return extract_grid_schedule(
            p, o, 'SweepGrid', rect=((-a1m, a1m), (-a2m, a2m)))

    def stage2_rect(p, o):
        pol = json.load(open(p))['policy']
        e = [dec_fraction(x) for x in pol['EXCL_OLD']]
        return extract_grid_schedule(
            p, o, 'Stage2Grid', rect=((e[0], e[1]), (e[2], e[3])))

    jobs = [
        ('huang_star_interior_%s.json' % t, extract_star_interior),
        ('huang_sweep_%s.json' % t, sweep_rect),
        ('huang_region1_%s.json' % t, extract_region1_schedule),
        ('huang_region1_%s.json' % t, extract_region1_bdef),
        ('huang_sweep2_%s.json' % t, stage2_rect),
    ]
    for name, fn in jobs:
        path = os.path.join(r, name)
        if not os.path.exists(path):
            print(f'skip (not present yet): {name}')
            continue
        out_sha = fn(path, args.out)
        if out_sha is None:
            continue
        label = f'{name}:{fn.__name__}'
        manifest['inputs'][label] = sha256_file(path)
        manifest['outputs'][label] = out_sha
        print(f'extracted {label} -> {out_sha[:16]}')
    with open(os.path.join(args.out, 'manifest.json'), 'w',
              encoding='utf-8', newline='\n') as f:
        json.dump(manifest, f, indent=1, sort_keys=True)
    print('wrote', os.path.join(args.out, 'manifest.json'))


if __name__ == '__main__':
    main()
